class Fibonacci
  def adding num_1,num_2,limit
    result = 0
    sum = 0
    while(result < limit) do
        if ((result % 2) == 0)
            sum += result
        end
        result = num_1 + num_2
        num_2 = num_1
        num_1 = result
    end
    return sum
  end

end
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
